### Generated by rprotoc. DO NOT EDIT!
### <proto file: ./large.proto>
# package large;
# message Data {
# optional string string_field0 = 1;
# optional string string_field1 = 2;
# optional string string_field2 = 3;
# optional string string_field3 = 4;
# optional string string_field4 = 5;
# optional string string_field5 = 6;
# optional string string_field6 = 7;
# optional string string_field7 = 8;
# optional string string_field8 = 9;
# optional string string_field9 = 10;
# optional string string_field10 = 11;
# optional string string_field11 = 12;
# optional string string_field12 = 13;
# optional string string_field13 = 14;
# optional string string_field14 = 15;
# optional string string_field15 = 16;
# optional string string_field16 = 17;
# optional string string_field17 = 18;
# optional string string_field18 = 19;
# optional string string_field19 = 20;
# optional string string_field20 = 21;
# optional string string_field21 = 22;
# optional string string_field22 = 23;
# optional string string_field23 = 24;
# optional string string_field24 = 25;
# optional string string_field25 = 26;
# optional string string_field26 = 27;
# optional string string_field27 = 28;
# optional string string_field28 = 29;
# optional string string_field29 = 30;
# optional string string_field30 = 31;
# optional string string_field31 = 32;
# optional string string_field32 = 33;
# optional string string_field33 = 34;
# optional string string_field34 = 35;
# optional string string_field35 = 36;
# optional string string_field36 = 37;
# optional string string_field37 = 38;
# optional string string_field38 = 39;
# optional string string_field39 = 40;
# optional string string_field40 = 41;
# optional string string_field41 = 42;
# optional string string_field42 = 43;
# optional string string_field43 = 44;
# optional string string_field44 = 45;
# optional string string_field45 = 46;
# optional string string_field46 = 47;
# optional string string_field47 = 48;
# optional string string_field48 = 49;
# optional string string_field49 = 50;
# 
# optional int32 int_field0 = 51;
# optional int32 int_field1 = 52;
# optional int32 int_field2 = 53;
# optional int32 int_field3 = 54;
# optional int32 int_field4 = 55;
# optional int32 int_field5 = 56;
# optional int32 int_field6 = 57;
# optional int32 int_field7 = 58;
# optional int32 int_field8 = 59;
# optional int32 int_field9 = 60;
# optional int32 int_field10 = 61;
# optional int32 int_field11 = 62;
# optional int32 int_field12 = 63;
# optional int32 int_field13 = 64;
# optional int32 int_field14 = 65;
# optional int32 int_field15 = 66;
# optional int32 int_field16 = 67;
# optional int32 int_field17 = 68;
# optional int32 int_field18 = 69;
# optional int32 int_field19 = 70;
# optional int32 int_field20 = 71;
# optional int32 int_field21 = 72;
# optional int32 int_field22 = 73;
# optional int32 int_field23 = 74;
# optional int32 int_field24 = 75;
# optional int32 int_field25 = 76;
# optional int32 int_field26 = 77;
# optional int32 int_field27 = 78;
# optional int32 int_field28 = 79;
# optional int32 int_field29 = 80;
# optional int32 int_field30 = 81;
# optional int32 int_field31 = 82;
# optional int32 int_field32 = 83;
# optional int32 int_field33 = 84;
# optional int32 int_field34 = 85;
# optional int32 int_field35 = 86;
# optional int32 int_field36 = 87;
# optional int32 int_field37 = 88;
# optional int32 int_field38 = 89;
# optional int32 int_field39 = 90;
# optional int32 int_field40 = 91;
# optional int32 int_field41 = 92;
# optional int32 int_field42 = 93;
# optional int32 int_field43 = 94;
# optional int32 int_field44 = 95;
# optional int32 int_field45 = 96;
# optional int32 int_field46 = 97;
# optional int32 int_field47 = 98;
# optional int32 int_field48 = 99;
# optional int32 int_field49 = 100;
# 
# }
require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Large
  class Data < ::Protobuf::Message
    defined_in __FILE__
    optional :string, :string_field0, 1
    optional :string, :string_field1, 2
    optional :string, :string_field2, 3
    optional :string, :string_field3, 4
    optional :string, :string_field4, 5
    optional :string, :string_field5, 6
    optional :string, :string_field6, 7
    optional :string, :string_field7, 8
    optional :string, :string_field8, 9
    optional :string, :string_field9, 10
    optional :string, :string_field10, 11
    optional :string, :string_field11, 12
    optional :string, :string_field12, 13
    optional :string, :string_field13, 14
    optional :string, :string_field14, 15
    optional :string, :string_field15, 16
    optional :string, :string_field16, 17
    optional :string, :string_field17, 18
    optional :string, :string_field18, 19
    optional :string, :string_field19, 20
    optional :string, :string_field20, 21
    optional :string, :string_field21, 22
    optional :string, :string_field22, 23
    optional :string, :string_field23, 24
    optional :string, :string_field24, 25
    optional :string, :string_field25, 26
    optional :string, :string_field26, 27
    optional :string, :string_field27, 28
    optional :string, :string_field28, 29
    optional :string, :string_field29, 30
    optional :string, :string_field30, 31
    optional :string, :string_field31, 32
    optional :string, :string_field32, 33
    optional :string, :string_field33, 34
    optional :string, :string_field34, 35
    optional :string, :string_field35, 36
    optional :string, :string_field36, 37
    optional :string, :string_field37, 38
    optional :string, :string_field38, 39
    optional :string, :string_field39, 40
    optional :string, :string_field40, 41
    optional :string, :string_field41, 42
    optional :string, :string_field42, 43
    optional :string, :string_field43, 44
    optional :string, :string_field44, 45
    optional :string, :string_field45, 46
    optional :string, :string_field46, 47
    optional :string, :string_field47, 48
    optional :string, :string_field48, 49
    optional :string, :string_field49, 50
    optional :int32, :int_field0, 51
    optional :int32, :int_field1, 52
    optional :int32, :int_field2, 53
    optional :int32, :int_field3, 54
    optional :int32, :int_field4, 55
    optional :int32, :int_field5, 56
    optional :int32, :int_field6, 57
    optional :int32, :int_field7, 58
    optional :int32, :int_field8, 59
    optional :int32, :int_field9, 60
    optional :int32, :int_field10, 61
    optional :int32, :int_field11, 62
    optional :int32, :int_field12, 63
    optional :int32, :int_field13, 64
    optional :int32, :int_field14, 65
    optional :int32, :int_field15, 66
    optional :int32, :int_field16, 67
    optional :int32, :int_field17, 68
    optional :int32, :int_field18, 69
    optional :int32, :int_field19, 70
    optional :int32, :int_field20, 71
    optional :int32, :int_field21, 72
    optional :int32, :int_field22, 73
    optional :int32, :int_field23, 74
    optional :int32, :int_field24, 75
    optional :int32, :int_field25, 76
    optional :int32, :int_field26, 77
    optional :int32, :int_field27, 78
    optional :int32, :int_field28, 79
    optional :int32, :int_field29, 80
    optional :int32, :int_field30, 81
    optional :int32, :int_field31, 82
    optional :int32, :int_field32, 83
    optional :int32, :int_field33, 84
    optional :int32, :int_field34, 85
    optional :int32, :int_field35, 86
    optional :int32, :int_field36, 87
    optional :int32, :int_field37, 88
    optional :int32, :int_field38, 89
    optional :int32, :int_field39, 90
    optional :int32, :int_field40, 91
    optional :int32, :int_field41, 92
    optional :int32, :int_field42, 93
    optional :int32, :int_field43, 94
    optional :int32, :int_field44, 95
    optional :int32, :int_field45, 96
    optional :int32, :int_field46, 97
    optional :int32, :int_field47, 98
    optional :int32, :int_field48, 99
    optional :int32, :int_field49, 100
  end
end